[package]
name = "carddown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
blake3 = { version = "*", features = ["serde"] }
lazy_static = "*"
regex = "*"
serde = "*"
serde_json = "*"
