[package]
name = "carddown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
blake3 = { version = "*", features = ["serde"] }
chrono = { version = "*", features = ["serde"] }
clap = { version = "*", features = ["derive"] }
crossterm = "*"
env_logger = "*"
fixed = { version = "*", features = ["serde"] }
lazy_static = "*"
log = "*"
rand = "*"
ratatui = "*"
regex = "*"
serde = "*"
serde_json = "*"
walkdir = "*"

[dev-dependencies]
tempfile = "*"
